### ISSUE TITLE
契約内容 詳細view作成

### ISSUE THREAD

**Issue by toshikase** [toshikase/swap-trade#1]

**Comment by YusukeMukoyama** [comment]
動的リンクと契約詳細画面の見た目

**Comment by YusukeMukoyama** [comment]
１．想定元本：1億円、通貨：JPY  
２．契約日：2016年5月1日
３．満期日：2018年4月30日(契約日から二年後)
４．固定金利：2.00%
５．変動金利：TIBOR、現在適用金利 1.00%
6.  銀行が固定側か変動側かの情報(銀行側ポジション)
7. 取引先企業名
8.実行ステータス
9. 商品No.

※ 1~5, 7は契約締結時に入力される情報

**Comment by YusukeMukoyama** [comment]
test

**Comment by YusukeMukoyama** [comment]
test

**Comment by YusukeMukoyama** [comment]
Mongoのカラム

Mongo column: _id, contract_name, principal, contract_date, exeday, fixed_rate, float_rate, position, client_name, exe_status
日本語名: 商品ID(自動設定)、契約名、元本、契約日、満期日、固定金利、変動金利、銀行ポジション、取引先企業名、実行ステータス
